services:
  api:
    build: .

    container_name: task-api-container

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: "postgresql://postgres:taskapi1234@task-db.cmhgui44wadz.us-east-1.rds.amazonaws.com:5432/taskdb"
